language: go
go:
  - 1.4
  - 1.3
  - 1.2
  - tip
services:
  - redis
before_install:
  # install consul
  - wget https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip
  - unzip 0.5.0_linux_amd64.zip
  - sudo mv consul /bin/
  - consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul &
  # install etcd
  - wget https://github.com/coreos/etcd/releases/download/v2.0.9/etcd-v2.0.9-linux-amd64.tar.gz
  - tar xzf etcd-v2.0.9-linux-amd64.tar.gz
  - sudo mv etcd-v2.0.9-linux-amd64/etcd /bin/
  - etcd &
install:
  - go get github.com/tools/godep
  - go get golang.org/x/tools/cmd/cover
  - ./build
  - sudo ./install
script:
  - ./test
  - bash integration/consul/test.sh
  - bash integration/etcd/test.sh
  - bash integration/fs/test.sh
  - bash integration/redis/test.sh
