language: go
go:
  - 1.5
  - tip
script:
  - make static
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
      secure: "Dt3DD0nS3YhG1oZThnnfyTVitaBPVWzuYNYiVFeJJn8QsFiSw+PBUiQ8nG2rMikH73uw78epAzYPWgEodBbW+yRR7twH6ks55mWTAjIkmGrc7xamIab0gJCzSHcyu8U4QLiQ4eese6GlqOyYgBx8zG03kd9Lmqp+13imw0HSIDU="
  file:
    - ${TRAVIS_BUILD_DIR}/bin/renderizr-linux-amd64
    - ${TRAVIS_BUILD_DIR}/bin/renderizr-darwin-amd64
  on:
    repo: glerchundi/renderizr
    branch: master
    tags: true
    go: 1.5
